apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: guyhguy/wordpress-server:test
        name: wordpress
        env:
        - name: WP_HOME
          value: "http://dev-reshet.tv"
        - name: WP_SITEURL
          value: "http://dev-reshet.tv"
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim